name: Udacity-Project-3

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo 
        uses: actions/checkout@v2

      - name: Steup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8
          pip install pytest

      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: setup DVC to pull data
        uses: iterative/setup-dvc@v1
      
      - name: Run unit tests
        run: |
          ls
          pwd
          python -m pytest

      - name: Lint with flake8 
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      
